# Generated by Django 4.0.3 on 2022-03-11 15:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='profile',
            new_name='Team',
        ),
    ]
