# Generated by Django 4.0.3 on 2022-03-11 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_tasks_team_leader_remove_tasks_team_member'),
        ('user_app', '0002_rename_profile_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Team_Members', to='tasks.tasks'),
        ),
    ]
