# Generated by Django 4.0.3 on 2022-03-11 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_remove_team_team_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=20)),
                ('priority', models.CharField(choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low')], default='H', max_length=1)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('Assigned', 'Assigned'), ('InProgress', 'InProgress'), ('UnderReview', 'UnderReview'), ('Done', 'Done')], default='Done', max_length=20)),
                ('team_leader', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_leader', to='user_app.team')),
            ],
        ),
    ]
