# Generated by Django 4.0.3 on 2022-03-11 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='team_member',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='user_app.team'),
            preserve_default=False,
        ),
    ]
