# Generated by Django 4.0.3 on 2022-03-12 05:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_app', '0006_tasks_team_member'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team',
            new_name='Users',
        ),
    ]
