# Generated by Django 4.0.3 on 2022-03-12 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_profile_remove_users_user_delete_tasks_delete_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='team',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='team_member',
        ),
    ]
