# Generated by Django 4.0.3 on 2022-03-11 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_tasks_team_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='team_leader',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='team_member',
        ),
    ]
