# Generated by Django 4.0.3 on 2022-03-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_tasks_team_leader_remove_tasks_team_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('Assigned', 'Assigner'), ('InProgress', 'InProgress'), ('UnderReview', 'UnderReview'), ('Done', 'Done')], default='Done', max_length=20),
        ),
    ]
