# Generated by Django 4.0.3 on 2022-03-11 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_tasks'),
        ('tasks', '0005_alter_tasks_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='team_leader',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='user_app.team'),
            preserve_default=False,
        ),
    ]
