# Generated by Django 4.0.3 on 2022-03-12 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_tasks_team_leader'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
