# Generated by Django 4.0.3 on 2022-03-12 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0009_remove_profile_team_remove_profile_team_member'),
        ('tasks', '0008_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='assigned_to',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to', to='user_app.profile'),
            preserve_default=False,
        ),
    ]
