# Generated by Django 4.0.3 on 2022-03-12 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_team_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='assigned_to',
        ),
    ]
