# Generated by Django 4.0.3 on 2022-03-12 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_remove_team_assigned_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='name',
            new_name='task_name',
        ),
    ]
